
-- ROLLUP
SELECT
    DEPT_CODE,
    JOB_CODE,
    SUM(SALARY)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE, JOB_CODE)
ORDER BY 1;

-- CUBE
SELECT
    DEPT_CODE,
    JOB_CODE,
    SUM(SALARY)
FROM EMPLOYEE
GROUP BY CUBE(DEPT_CODE, JOB_CODE)
ORDER BY 1;
--> j7이 왜 두개가 나오는가? 전체 다 더한거랑, 부서코드가 NULL인 경우 두개 나눔

-- UNION

SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;
-- 집합 연산자의 유의할 점 : 두개의 쿼리문의 컬럼의 갯수와 타입이 같아야 함

-- JOIN 사용법

SELECT EMP_ID, EMP_NAME, DEPT_CODE
FROM EMPLOYEE;

SELECT DEPT_ID, DEPT_TITLE
FROM DEPARTMENT;

-- DEPT_CODE = DEPT_ID --> JOIN

SELECT EMP_ID, EMP_NAME, DEPT_TITLE
FROM EMPLOYEE INNER JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID);

-- 두 테이블의 컬럼 이름이 같을때 충돌하는 오류의 해결

-- ORACLE 전용구문
-- 테이블명.컬럼명표시 해줌 (원하는 테이블명을 적어주기) 
SELECT EMP_ID, EMP_NAME, PHONE, EMAIL, EMPLOYEE.JOB_CODE, JOB_NAME
FROM EMPLOYEE INNER JOIN JOB ON(EMPLOYEE.JOB_CODE = JOB.JOB_CODE);

-- ANSI 표준구문
-- USING 안에 있는 컬럼명은 JOIN된 테이블의 컬럼명
SELECT EMP_ID, EMP_NAME,  PHONE, EMAIL, JOB_CODE, JOB_NAME
FROM EMPLOYEE INNER JOIN JOB USING(JOB_CODE);

-- JOIN의 종류
-- 1. INNER JOIN 내부조인 : 교집합
-- 2. OUTER JOIN 외부조인 : 합집합
-- * LEFT OUTER JOIN : 
-- * RIGHT OUTER JOIN :
-- * FULL OUYER JOIN :

SELECT EMP_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE LEFT OUTER JOIN DEPARTMENT
ON (DEPT_CODE = DEPT_ID); --> () 조건없는 EMPLOYEE 나옴

SELECT EMP_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE RIGHT OUTER JOIN DEPARTMENT
ON (DEPT_CODE = DEPT_ID); --> () 조건없는 DEPARTMENT 나옴

SELECT EMP_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE FULL OUTER JOIN DEPARTMENT
ON (DEPT_CODE = DEPT_ID); ---> 둘 다 나옴

-- SELF JOIN
-- 같은 테이블을 조인하는 경우 (직원과 매니저 같이 출력)
SELECT EMP.EMP_ID "사번", EMP.EMP_NAME "직원명", EMP.DEPT_CODE "부서코드", 
        EMP.MANAGER_ID"매니저 사번", MANAGER.EMP_NAME "매니저 이름"
FROM EMPLOYEE EMP INNER JOIN EMPLOYEE MANAGER 
                    ON(EMP.MANAGER_ID = MANAGER.EMP_ID);

-- 도전문제
-- 자신이 관리하고 있는 사원의 이름,급여 및 직급이 어떻게 되는지 검색하여라.
SELECT 
    MANAGER.EMP_NAME "매니저이름", EMP.EMP_NAME "사원 이름 ", 
    EMP.SALARY "사원 급여", EMP.JOB_CODE "사원 직급"
FROM EMPLOYEE EMP INNER JOIN EMPLOYEE MANAGER ON (EMP.MANAGER_ID = MANAGER.EMP_ID);