
--##  시퀀스 간단 예제 ##
--KH_MEMBER 테이블을 생성
--컬럼
--MEMBER_ID	NUNBER
--MEMBER_NAME	VARCHAR2(20)
--MEMBER_AGE	NUMBER
--MEMBER_JOIN_COM	NUMBER

CREATE TABLE KH_MEMBER (
    MEMBER_ID NUMBER,
    MEMBER_NAME VARCHAR2(20),
    MEMBER_AGE	NUMBER,
    MEMBER_JOIN_COM	NUMBER
);

--ID값은 500 번 부터 시작하여 10씩 증가하여 저장 하고자 함
--JOIN_COM 값은 1번부터 시작하여 1씩 증가하여 저장 해야 함
--(ID 값과 JOIN_COM 값의 MAX는 10000으로 설정)

CREATE SEQUENCE SEQ_MEMBER_ID
START WITH 500
INCREMENT BY 10
MAXVALUE 10000
NOCYCLE 
NOCACHE;

CREATE SEQUENCE SEQ_MEMBER_JOIN_COM
START WITH 1
INCREMENT BY 1
MAXVALUE 10000
NOCYCLE 
NOCACHE;

--이때 해당 사원들의 정보를 INSERT 해야 함
--ID 값과 JOIN_COM은 SEQUENCE 를 이용하여 정보를 넣고자 함

INSERT INTO KH_MEMBER
VALUES(SEQ_MEMBER_ID.NEXTVAL,'안창림', 27, SEQ_MEMBER_JOIN_COM.NEXTVAL);
INSERT INTO KH_MEMBER 
VALUES(SEQ_MEMBER_ID.NEXTVAL,'신유빈', 18, SEQ_MEMBER_JOIN_COM.NEXTVAL);
INSERT INTO KH_MEMBER 
VALUES(SEQ_MEMBER_ID.NEXTVAL,'강이슬', 28, SEQ_MEMBER_JOIN_COM.NEXTVAL);
INSERT INTO KH_MEMBER 
VALUES(SEQ_MEMBER_ID.NEXTVAL,'황선우', 19, SEQ_MEMBER_JOIN_COM.NEXTVAL);
INSERT INTO KH_MEMBER 
VALUES(SEQ_MEMBER_ID.NEXTVAL,'안산', 21, SEQ_MEMBER_JOIN_COM.NEXTVAL);

SELECT * FROM KH_MEMBER;

-- 시퀀스 데이터 딕셔너리 뷰 조회하기
SELECT * FROM USER_SEQUENCES;

