--COMMIT / ROLLBACK / SAVEPOINT 
CREATE TABLE USER_TRANSACTION (
    USER_NO NUMBER UNIQUE,
    USER_ID VARCHAR2(50) PRIMARY KEY,
    USER_PWD CHAR(30) NOT NULL
);

SELECT * FROM USER_TRANSACTION;

INSERT INTO USER_TRANSACTION
VALUES(1 , 'TEST1', 'PASS1');
INSERT INTO USER_TRANSACTION
VALUES(2 , 'TEST2', 'PASS2');
INSERT INTO USER_TRANSACTION
VALUES(3 , 'TEST3', 'PASS3');

COMMIT;

INSERT INTO USER_TRANSACTION
VALUES(4 , 'TEST4', 'PASS4');
SELECT * FROM USER_TRANSACTION;

ROLLBACK; -- 커밋한 시점으로 되돌려줌

-- SAVE POINT 임시저장
INSERT INTO USER_TRANSACTION
VALUES(4 , 'TEST4', 'PASS4');
SAVEPOINT TEMP1;
INSERT INTO USER_TRANSACTION
VALUES(5 , 'TEST5', 'PASS5');
SELECT * FROM USER_TRANSACTION;
ROLLBACK TO TEMP1; --> 임시저장 위치까지 포함
ROLLBACK; --> 그냥 다 취소

UPDATE USER_TRANSACTION
SET USER_PWD = 'BW0707'
WHERE USER_NO = 5;
COMMIT;
SELECT * FROM USER_TRANSACTION;