SHOW USER;

SELECT * FROM KHLUV.COFFEE;

INSERT INTO KHLUV.COFFEE
VALUES('맥스웰하우스', 20000, 'MAXWELLHOUSE');
COMMIT; --> 여기서 커밋을 해야 KHLUV에서도 값이 추가됨

INSERT INTO KHLUV.COFFEE
VALUES('네스프레소', 60000, 'NESPRESSO');
COMMIT;

