 -- 회원 테이블 입니다.
    -- 회원 아이디, MEMBER_ID, VARCHAR2(30), PRIMARY KEY
    -- 회원 비밀번호, MEMBER_PWD, VARCHAR2(30), NOT NULL
    -- 회원 이름, MEMBER_NAME, VARCHAR2(30), NOT NULL
    -- 회원 성별, MEMBER_GENDER, VARCHAR2(6), CHECK(F,M)
    -- 회원 나이, MEMBER_AGE, NUMBER, NOT NULL
    -- 회원 이메일, MEMBER_EMAIL, VARCHAR2(50)
    -- 회원 전화번호, MEMBER_PHONE, VARCHAR2(11)
    -- 회원 주소, MEMBER_ADDRESS, VARCHAR2(10000)
    -- 회원 취미, MEMBER_HOBBY, VARCHAR2(50)
    -- 가입날짜, ENROLL_DATE, DEFAULT SYSDATE
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR2(30) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(30) NOT NULL,
    MEMBER_NAME VARCHAR2(30) NOT NULL,
    MEMBER_GENDER VARCHAR2(6) CHECK(MEMBER_GENDER IN('F','M')),
    MEMBER_AGE NUMBER NOT NULL,
    MEMBER_EMAIL VARCHAR2(50),
    MEMBER_PHONE VARCHAR2(16),
    MEMBER_ADDRESS VARCHAR2(1000),
    MEMBER_HOBBY VARCHAR2(50),
    ENROLL_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_GENDER IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_AGE IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_HOBBY IS '회원 아이디';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원 아이디';
COMMENT ON TABLE MEMBER IS '회원 테이블';

SELECT *
FROM ALL_TAB_COMMENTS
WHERE TABLE_NAME = 'MEMBER';
    
INSERT INTO MEMBER
VALUES('admin', 'admin', '관리자', 'M', 29 ,
        'admin@kh.com','01012345678', '서울시 송파구','코딩',SYSDATE);
        
COMMIT;
SELECT * FROM MEMBER;
